input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [app] {
    mutate {
      add_field => { "service" => "%{app}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "microservices-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
