server.port=8080
spring.application.name=developer-service

# Zipkin endpoint
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
# Трассировка 100% запросов (для демонстрации)
management.tracing.sampling.probability=1.0

management.endpoints.web.exposure.include=health,info
