app.name=Developer Service
app.version=1.0.0
server.port=8080

developer.default.specialization=Backend
developer.default.minRating=1.0
developer.default.maxProjects=5

eureka.instance.preferIpAddress=true
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone=http://localhost:8070/eureka/

logging.level.com.example=INFO
