# Настройки для продакшена
greeting.message=Добро пожаловать в продакшен!

# База данных для продакшена
db.host=prod-db.company.com
db.port=5432
db.name=developerservice_prod
db.username=prod_admin
db.password=SuperSecurePass123!

# Настройки для prod разработчиков
developer.default.specialization=Fullstack
developer.default.minRating=4.0
